import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallDevice = width < 375;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    position: 'relative',
  },
  backgroundImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    opacity: 0.7,
  },
  mainTitle: {
    fontFamily: 'Orbitron_700Bold',
    fontSize: isSmallDevice ? 28 : 32,
    color: '#fff',
    fontWeight: 'bold',
    marginTop: height * 0.1,
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 2,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    paddingHorizontal: 20,
  },
  mainImage: {
    width: width * 0.8,
    height: width * 0.8,
    maxWidth: 400,
    maxHeight: 400,
    resizeMode: 'contain',
    borderRadius: 10,
    marginBottom: 20,
    alignSelf: 'center',
  },
  buttonContainer: {
    width: width * 0.9,
    maxWidth: 350,
    alignSelf: 'center',
    marginVertical: 6,
  },
  customButton: {
    paddingVertical: isSmallDevice ? 10 : 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#ff0000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#ff0000',
    overflow: 'hidden',
  },
  buttonNoiseOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.1,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'rgba(255,0,0,0.1)',
  },
  buttonText: {
    color: '#1e1e1e',
    fontSize: isSmallDevice ? 14 : 16,
    fontWeight: '600',
    fontFamily: 'Orbitron_400Regular',
    letterSpacing: 1,
  },
  playingButton: {
    borderColor: '#ff0000',
    borderWidth: 2,
    shadowColor: '#ff0000',
    shadowOpacity: 0.8,
    shadowRadius: 10,
    transform: [{ scale: 1.05 }],
  },
  playingText: {
    color: '#ff0000',
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 15,
    padding: 20,
    width: '100%',
    maxHeight: height * 0.8,
    borderWidth: 1,
    borderColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalTitle: {
    fontSize: isSmallDevice ? 24 : 28,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 25,
    fontFamily: 'Orbitron_700Bold',
    letterSpacing: 2,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  instagramCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  instagramImage: {
    width: '100%',
    height: width * 0.5,
    borderRadius: 12,
    marginBottom: 12,
    resizeMode: 'cover',
  },
  instagramTitle: {
    color: '#fff',
    fontSize: isSmallDevice ? 16 : 18,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Orbitron_400Regular',
    letterSpacing: 2,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  pageContainer: {
    flex: 1,
    width: '100%',
    paddingTop: height * 0.08,
  },
  contentContainer: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    marginHorizontal: 15,
    borderRadius: 10,
  },
  separator: {
    height: 1,
    backgroundColor: '#ffffff',
    width: '60%',
    alignSelf: 'center',
    marginVertical: 20,
    opacity: 0.3,
  },
  pageText: {
    fontFamily: 'Orbitron_400Regular',
    fontSize: isSmallDevice ? 14 : 16,
    color: '#ffffff',
    marginBottom: 20,
    lineHeight: 24,
    textAlign: 'center',
  },
  releaseTitle: {
    fontFamily: 'Orbitron_700Bold',
    fontSize: isSmallDevice ? 18 : 20,
    color: '#ff0000',
    marginBottom: 10,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
    textAlign: 'center',
  },
  releaseText: {
    fontFamily: 'Orbitron_400Regular',
    fontSize: isSmallDevice ? 14 : 16,
    color: '#ffffff',
    marginBottom: 30,
    lineHeight: 24,
    textAlign: 'center',
  },
  centeredContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  centeredImage: {
    width: width * 0.7,
    height: width * 0.7,
    maxWidth: 300,
    maxHeight: 300,
    marginVertical: 20,
    alignSelf: 'center',
  },
  menuButton: {
    position: 'absolute',
    top: height * 0.05,
    left: 20,
    zIndex: 999,
    padding: 10,
  },
  menuButtonText: {
    color: '#ff0000',
    fontSize: 30,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    fontFamily: 'Orbitron_700Bold',
  },
  menu: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: width * 0.8,
    maxWidth: 300,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    zIndex: 998,
    borderRightWidth: 1,
    borderRightColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: height * 0.05,
    borderBottomWidth: 1,
    borderBottomColor: '#ff0000',
  },
  menuTitle: {
    color: '#ff0000',
    fontSize: isSmallDevice ? 18 : 20,
    fontFamily: 'Orbitron_700Bold',
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  closeButton: {
    color: '#ff0000',
    fontSize: 24,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  menuContent: {
    flex: 1,
  },
  menuSection: {
    marginTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 0, 0, 0.3)',
    paddingBottom: 20,
  },
  menuSectionTitle: {
    color: '#ff0000',
    fontSize: isSmallDevice ? 16 : 18,
    fontFamily: 'Orbitron_700Bold',
    paddingHorizontal: 20,
    marginBottom: 10,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  loginContainer: {
    width: width * 0.9,
    maxWidth: 400,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderRadius: 15,
    padding: 25,
    alignSelf: 'center',
    marginTop: height * 0.15,
    borderWidth: 2,
    borderColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  terminalText: {
    fontFamily: 'Orbitron_700Bold',
    fontSize: 24,
    color: '#ff0000',
    textAlign: 'center',
    marginBottom: 30,
    textTransform: 'uppercase',
    letterSpacing: 3,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  scanline: {
    position: 'absolute',
    width: width,
    height: 2,
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
    zIndex: 2,
  },
  hackText: {
    color: '#33ff33',
    fontFamily: 'Orbitron_400Regular',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: '#33ff33',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  codeContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  codeInputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
  },
  codeInput: {
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: '#ff0000',
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
    margin: 5,
    textAlign: 'center',
    fontSize: 24,
    color: '#ff0000',
    fontFamily: 'Orbitron_700Bold',
  },
  accessKeyContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  accessKeyInput: {
    width: '100%',
    height: 50,
    borderWidth: 2,
    borderColor: '#33ff33',
    backgroundColor: 'rgba(51, 255, 51, 0.1)',
    padding: 10,
    color: '#33ff33',
    fontSize: 18,
    fontFamily: 'Orbitron_400Regular',
    textAlign: 'center',
  },
  biometricContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  biometricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: 180,
  },
  biometricCell: {
    width: 50,
    height: 50,
    margin: 5,
    borderWidth: 1,
    borderColor: '#ff0000',
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
  },
  biometricCellActive: {
    backgroundColor: 'rgba(255, 0, 0, 0.5)',
    borderColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
  },
  hackButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#ff0000',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#ff0000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  hackButtonDisabled: {
    borderColor: '#660000',
    opacity: 0.7,
  },
  hackButtonText: {
    color: '#ff0000',
    fontSize: 16,
    fontFamily: 'Orbitron_700Bold',
    letterSpacing: 2,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  errorText: {
    color: '#ff0000',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Orbitron_400Regular',
    marginBottom: 20,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  warningText: {
    color: '#ff0000',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'Orbitron_400Regular',
    opacity: 0.7,
    textShadowColor: '#ff0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  loginFormContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    backdropFilter: 'blur(10px)',
    padding: 30,
    borderRadius: 20,
    width: '90%',
    maxWidth: 400,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  loginTitle: {
    fontFamily: 'Orbitron_700Bold',
    fontSize: 28,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 30,
    letterSpacing: 3,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  inputContainer: {
    gap: 15,
    marginBottom: 25,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 15,
    color: '#ffffff',
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  loginButton: {
    backgroundColor: '#4A90E2',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#4A90E2',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  loginButtonDisabled: {
    backgroundColor: 'rgba(74, 144, 226, 0.5)',
    shadowOpacity: 0,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
  },
  warningText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  secretContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderRadius: 20,
    padding: 25,
    margin: 20,
    borderWidth: 1,
    borderColor: '#4A90E2',
    shadowColor: '#4A90E2',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  secretTitle: {
    fontSize: 32,
    color: '#4A90E2',
    textAlign: 'center',
    fontFamily: 'Orbitron_700Bold',
    marginBottom: 30,
    textTransform: 'uppercase',
    letterSpacing: 3,
    textShadowColor: '#4A90E2',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  contentSection: {
    alignItems: 'center',
  },
  secretText: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 24,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 30,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    color: '#4A90E2',
    fontSize: 36,
    fontFamily: 'Orbitron_700Bold',
    marginBottom: 5,
    textShadowColor: '#4A90E2',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  statLabel: {
    color: '#ffffff',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  actionButton: {
    backgroundColor: 'transparent',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#4A90E2',
    marginTop: 20,
  },
  actionButtonText: {
    color: '#4A90E2',
    fontSize: 16,
    fontFamily: 'Orbitron_700Bold',
    letterSpacing: 2,
    textShadowColor: '#4A90E2',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
}); 